name: smart_file_storage
description: A modern Smart File Storage & Cloud Manager app with neumorphism design
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI / Fonts
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0

  # Permissions
  permission_handler: ^12.0.1

  # File system utilities
  path_provider: ^2.1.5
  file_manager: ^1.0.2

  # FIX VERSION COMPATIBLE WITH CODEMAGIC
  open_file_plus: ^3.4.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
