name: smart_file_storage
description: A modern Smart File Storage & Cloud Manager app with neumorphism design
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Icons & Fonts
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0

  # Permissions
  permission_handler: ^12.0.1

  # File & Storage
  path_provider: ^2.1.5
  file_manager: ^1.0.2

  # REPLACEMENT FOR open_file_plus (compatible & stable)
  open_file: ^3.3.2
  camera: ^0.11.3
  supabase_flutter: ^2.10.3
  file_picker: ^10.3.7
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
